apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mojyy9klf-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mojyy9klf-go 
  name: mojyy9klf-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mojyy9klf-go 
